name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build the Angular app
        run: |
          npm install -g @angular/cli
          npm install
          ng build --prod

      - name: Build Docker image
        run: |
          docker build -t your-app-name .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag your-app-name $DOCKER_USERNAME/your-app-name:latest
          docker push $DOCKER_USERNAME/your-app-name:latest
